import { BuildingType } from './types';

export const BUILDINGS: BuildingType[] = [
    {
        id: 'wall_h',
        name: 'Duvar (Yatay)',
        type: 'defense',
        width: 1,
        height: 1,
        cost: 50,
        emoji: '🧱',
        description: 'Düşmanları durdurur.',
    },
    {
        id: 'wall_v',
        name: 'Duvar (Dikey)',
        type: 'defense',
        width: 1,
        height: 1,
        cost: 50,
        emoji: '🧱',
        description: 'Düşmanları durdurur.',
    },
    {
        id: 'tower',
        name: 'Gözetleme Kulesi',
        type: 'defense',
        width: 2,
        height: 2,
        cost: 250,
        emoji: '🗼',
        description: 'Uzakları görür.',
    },
    {
        id: 'house',
        name: 'Kulübe',
        type: 'economy',
        width: 2,
        height: 2,
        cost: 150,
        emoji: '🏠',
        description: 'İşçilerin yaşar.',
    },
    {
        id: 'barracks',
        name: 'Kışla',
        type: 'military',
        width: 3,
        height: 3,
        cost: 500,
        emoji: '⚔️',
        description: 'Asker eğitir.',
    },
    {
        id: 'farm',
        name: 'Çiftlik',
        type: 'economy',
        width: 2,
        height: 2,
        cost: 200,
        emoji: '🌾',
        description: 'Yiyecek üretir.',
    },
    {
        id: 'castle',
        name: 'Ana Kale',
        type: 'defense',
        width: 4,
        height: 4,
        cost: 1000,
        emoji: '🏰',
        description: 'Krallığın kalbi.',
    },
    {
        id: 'tree',
        name: 'Ağaç',
        type: 'decoration',
        width: 1,
        height: 1,
        cost: 25,
        emoji: '🌳',
        description: 'Doğal güzellik.',
    },
    {
        id: 'fountain',
        name: 'Çeşme',
        type: 'decoration',
        width: 2,
        height: 2,
        cost: 300,
        emoji: '⛲',
        description: 'Su sesi huzur verir.',
    }
];

export const GRID_SIZE = 20; // 20x20 grid
export const TILE_SIZE = 40; // 40px per tile
