import { BuildingType } from './types';
import i18n from '../../i18n';

export const getBuildings = (): BuildingType[] => [
    {
        id: 'wall_h',
        name: i18n.t('buildings.wall_h_name'),
        type: 'defense',
        width: 1,
        height: 1,
        cost: 50,
        emoji: '🧱',
        description: i18n.t('buildings.wall_h_desc'),
    },
    {
        id: 'wall_v',
        name: i18n.t('buildings.wall_v_name'),
        type: 'defense',
        width: 1,
        height: 1,
        cost: 50,
        emoji: '🧱',
        description: i18n.t('buildings.wall_v_desc'),
    },
    {
        id: 'tower',
        name: i18n.t('buildings.tower_name'),
        type: 'defense',
        width: 2,
        height: 2,
        cost: 250,
        emoji: '🗼',
        description: i18n.t('buildings.tower_desc'),
    },
    {
        id: 'house',
        name: i18n.t('buildings.house_name'),
        type: 'economy',
        width: 2,
        height: 2,
        cost: 150,
        emoji: '🏠',
        description: i18n.t('buildings.house_desc'),
    },
    {
        id: 'barracks',
        name: i18n.t('buildings.barracks_name'),
        type: 'military',
        width: 3,
        height: 3,
        cost: 500,
        emoji: '⚔️',
        description: i18n.t('buildings.barracks_desc'),
    },
    {
        id: 'farm',
        name: i18n.t('buildings.farm_name'),
        type: 'economy',
        width: 2,
        height: 2,
        cost: 200,
        emoji: '🌾',
        description: i18n.t('buildings.farm_desc'),
    },
    {
        id: 'castle',
        name: i18n.t('buildings.castle_name'),
        type: 'defense',
        width: 4,
        height: 4,
        cost: 1000,
        emoji: '🏰',
        description: i18n.t('buildings.castle_desc'),
    },
    {
        id: 'tree',
        name: i18n.t('buildings.tree_name'),
        type: 'decoration',
        width: 1,
        height: 1,
        cost: 25,
        emoji: '🌳',
        description: i18n.t('buildings.tree_desc'),
    },
    {
        id: 'fountain',
        name: i18n.t('buildings.fountain_name'),
        type: 'decoration',
        width: 2,
        height: 2,
        cost: 300,
        emoji: '⛲',
        description: i18n.t('buildings.fountain_desc'),
    }
];

export const GRID_SIZE = 20; // 20x20 grid
export const TILE_SIZE = 40; // 40px per tile
